name: PartyAnimals
description: A web app that uses a lot of animals to make and customize a party.
# version: 1.0.0
# homepage: https://github.com/MaxSuleymanov/angularcource/tree/master/PartyAnimals
# author: Maxim Suleymanov <maxim.suleymanov@team.wrike.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_forms: ^2.1.2

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  test: ^1.5.1